// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZpRr-mAsTB-f9eezq_kOWrG8B-jxmHIU',
    appId: '1:697166472093:web:abb8ec14c466f16e028574',
    messagingSenderId: '697166472093',
    projectId: 'freshharvest-bf081',
    authDomain: 'freshharvest-bf081.firebaseapp.com',
    storageBucket: 'freshharvest-bf081.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTqnGfXWbd1psohZenJKUeT9O6DYZQdCg',
    appId: '1:697166472093:android:3bbfba4d89b8dcaf028574',
    messagingSenderId: '697166472093',
    projectId: 'freshharvest-bf081',
    storageBucket: 'freshharvest-bf081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6dAH7BVuPn3Yg8vCwNsw1ABnxGJK1or0',
    appId: '1:697166472093:ios:f3acb3de0a891208028574',
    messagingSenderId: '697166472093',
    projectId: 'freshharvest-bf081',
    storageBucket: 'freshharvest-bf081.firebasestorage.app',
    iosBundleId: 'com.example.freshharvest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6dAH7BVuPn3Yg8vCwNsw1ABnxGJK1or0',
    appId: '1:697166472093:ios:f3acb3de0a891208028574',
    messagingSenderId: '697166472093',
    projectId: 'freshharvest-bf081',
    storageBucket: 'freshharvest-bf081.firebasestorage.app',
    iosBundleId: 'com.example.freshharvest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZpRr-mAsTB-f9eezq_kOWrG8B-jxmHIU',
    appId: '1:697166472093:web:8133dbe72cd6bb8e028574',
    messagingSenderId: '697166472093',
    projectId: 'freshharvest-bf081',
    authDomain: 'freshharvest-bf081.firebaseapp.com',
    storageBucket: 'freshharvest-bf081.firebasestorage.app',
  );
}
